using System.Text.Json.Nodes;
using Microsoft.AspNetCore.Mvc;
using Products.Models;
using Products.Services;
using Products.ServiceErrors;
using ErrorOr;
using Products.Contracts;

namespace Products.Controllers;

[Route("[controller]")]
public class ProductsController : ApiController {
// every time a new request is sent to the service, 
// the framework creates a new controller object
	private readonly IProductsService _productsService;
	private readonly IMessageProducer _messageProducerService;

	public ProductsController(IProductsService productsService, IMessageProducer messageProducer) {
		_productsService = productsService;
		_messageProducerService =  messageProducer;
	}

	[HttpGet]
	public IEnumerable<ProductDto> GetAllProducts() {
		var productsList = _productsService.GetAllProducts()
			.Select(product => product.AsDto());
		
		return productsList;
	}

	[HttpGet("{id:int}")]
	public ActionResult<ProductDto> GetProductById(int id) {
		var product = _productsService.GetProductById(id);
		if(product == null) {
			return NotFound("The product you requested does not exist");
		}
		return product.AsDto();
	}


	/*public IActionResult GetProductById(int id){
		ErrorOr<Product> getProductResult = _productsService.GetProductById(id: id);
		
		// this line summarizes the code that is commented
		return getProductResult.Match(
			product => Ok(MapProductResponse(product)),
			errors => Problem(errors)
		);
		
		
		/* if (getProductResult.IsError && getProductResult.FirstError == Errors.Products.NotFound) {
			return NotFound();
		}

		Product product = getProductResult.Value;

		var response = new ProductResponse(
			product.ID,
			product.Title,
			product.Description,
			product.Price,
			product.Brand,
			product.Category
		);

		return Ok(response); *//*
	}*/
	/*[HttpGet("{id:int}")]
	public ActionResult<ProductDto> GetProductById(int id){
		var product = _productsService.GetProductById(id);
		return Ok();
	}*/

	[HttpPost]
	public IActionResult CreateProduct(CreateOrUpdateProductDto request) {
		var product = new Product(
			// this is not very accurate, but for example purposes, it suffices.
			// in reality it should be autogenerated
			_productsService.GetProductCount() + 1, 
			request.Name,
			request.Description,
			request.Price, 
			request.Brand,
			request.Category
		);
		
		_productsService.AddProduct(product);
		//_messageProducerService.SendMessage<Product>(product);

		return CreatedAtAction(nameof(GetProductById), new { id = product.ID }, product);
	}

	[HttpPut("{id:int}")]
	public IActionResult UpdateProduct(int id, CreateOrUpdateProductDto request) {

		var existingProduct = _productsService.GetProductById(id);		
		if (existingProduct == null) {
			return NotFound("The requested product does not exist");
		}

		existingProduct.Name = request.Name;
		existingProduct.Description = request.Description;
		existingProduct.Brand = request.Brand;
		existingProduct.Category = request.Category;
		existingProduct.Price = request.Price;

		return NoContent();
	}
}